# Generated by Django 4.2.16 on 2024-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
