# Generated by Django 4.2.16 on 2024-10-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0002_alter_menuitem_options_remove_menuitem_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="named_url",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="url",
        ),
    ]
