# Generated by Django 4.2.16 on 2024-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0003_remove_menuitem_named_url_remove_menuitem_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
